#define SUBPROG_CLAVE           257
#define TIPO_PRIM               258
#define TIPO_LISTA              259
#define NOMB_IF                 260
#define NOMB_THEN               261
#define NOMB_ELSE               262
#define NOMB_WHILE              263
#define NOMB_FOR                264
#define NOMB_ENTRADA            265
#define NOMB_SALIDA             266
#define LISTA_SENT              267
#define OP_TERN_PRIM_UN         268
#define OP_TERN_SEG             269
#define OP_BINARIO              270
#define OP_UNARIO               271
#define OP_UN_BIN               272
#define IDENTIFICADOR           273
#define CADENA                  274
#define CONSTANTE               275
#define PARIZQ                  276
#define PARDER                  277
#define CORIZQ                  278
#define CORDER                  279
#define LLAVIZQ                 280
#define LLAVDER                 281
#define COMA                    282
#define PYC                     283
#define ASIGN                   284
#define CABECERA_PROGRAMA       285
#define MARCA_INI_DECLAR_VARIABLES      286
#define MARCA_FIN_DECLAR_VARIABLES      287
